### ISSUE TITLE
Define your own outlet view to define different animations

### ISSUE THREAD

**Issue by ppcano** [billysbilling/ember-animated-outlet#9]
I have tried to animate outlet with a different approach.

Any opinions emberjs/ember.js#2542

Now, for example you could build custom animated views as:

```
  <div id="content">
    {{outlet view=App.FadeView}}
  </div>
```

``` js
var get = Ember.get, set = Ember.set;
App.FadeView = Ember.ContainerView.extend({

  classNames: ['animated-outlet'],

  outletName: null,
  outletContent: null,

  init: function () {
    this._super();
    this._outletContentAfter();
  },

  _outletContentAfter: Em.observer(function() {

    var newContent = get(this, 'outletContent');
    if (newContent) {

      var newView = Em.ContainerView.create({

        classNames: ['fade-container'],
        classNameBindings: ['isOut'],
        isOut: false,

        currentView: newContent,
        transitionEnd: function() {
          this.removeFromParent();
        }
      });

      var oldView = this.objectAt(0);
      if (oldView) {
        set(oldView, 'isOut', true);
      }
      this.pushObject(newView);
    }
  }, 'outletContent')

});

```

``` css
.fade-container {
  z-index: 1;
  opacity: 1;
  transition: opacity 1s ease-in-out;
}

.fade-container.is-out {
  z-index: 2;
  opacity: 0;

}
```
